Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "dev-server" do |dev|
    dev.vm.hostname = "dev-server"
    dev.vm.network "private_network", ip: "192.168.33.10"
    dev.vm.network "forwarded_port", guest: 8080, host: 8080
    dev.vm.network "forwarded_port", guest: 8090, host: 8090
    dev.vm.synced_folder ".", "/vagrant"

    dev.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end

    dev.vm.provision "shell", path: "../scripts/provision_dev.sh"
  end
end
