Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"

  config.vm.define "dev-server" do |dev|
    dev.vm.hostname = "dev-server"
    dev.vm.network "private_network", ip: "192.168.33.10"
    dev.vm.network "forwarded_port", guest: 8080, host: 8080
    dev.vm.network "forwarded_port", guest: 8090, host: 8090
    dev.vm.synced_folder ".", "/vagrant", disabled: true

    dev.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end

    dev.vm.provision "shell", path: "../scripts/provision_dev.sh"
  end

#   config.vm.define "test-server" do |test|
#     test.vm.hostname = "test-server"
#     test.vm.network "private_network", ip: "192.168.33.11"
#     test.vm.synced_folder ".", "/vagrant", disabled: true

#     test.vm.provider "virtualbox" do |vb|
#       vb.memory = "1024"
#       vb.cpus = 1
#     end

#     test.vm.provision "shell", path: "../scripts/provision_test.sh"
#   end
end
